version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: news_finder_db
    environment:
      POSTGRES_DB: news_finder
      POSTGRES_USER: news_finder_user
      POSTGRES_PASSWORD: news_finder_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U news_finder_user -d news_finder"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: news_finder_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@newsfinder.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
