sources:
- area: null
  category: Research Papers
  country: null
  dataset: null
  domains: null
  enabled: true
  language: null
  last_fetch: null
  max_items: 10
  max_results: 20
  method: null
  name: ArXiv AI Papers
  query: AI OR artificial intelligence OR machine learning
  sort_by: submittedDate
  sort_order: descending
  source_type: arxiv
  task: null
  update_interval: 3600
- area: null
  category: Computer Vision
  country: null
  dataset: null
  domains: null
  enabled: true
  language: null
  last_fetch: null
  max_items: 10
  max_results: 15
  method: null
  name: ArXiv Computer Vision
  query: computer vision OR image recognition
  sort_by: submittedDate
  sort_order: descending
  source_type: arxiv
  task: null
  update_interval: 3600
- area: null
  category: Natural Language Processing
  country: null
  dataset: null
  domains: null
  enabled: true
  language: null
  last_fetch: null
  max_items: 10
  max_results: 15
  method: null
  name: ArXiv NLP Papers
  query: natural language processing OR NLP OR transformers
  sort_by: submittedDate
  sort_order: descending
  source_type: arxiv
  task: null
  update_interval: 3600
- area: null
  category: technology
  country: us
  dataset: null
  domains: null
  enabled: true
  language: en
  last_fetch: null
  max_items: 15
  max_results: null
  method: null
  name: Tech News AI
  query: artificial intelligence OR AI
  sort_by: null
  sort_order: null
  source_type: newsapi
  task: null
  update_interval: 3600
- area: null
  category: business
  country: us
  dataset: null
  domains: null
  enabled: true
  language: en
  last_fetch: null
  max_items: 10
  max_results: null
  method: null
  name: Business AI News
  query: AI business OR artificial intelligence business
  sort_by: null
  sort_order: null
  source_type: newsapi
  task: null
  update_interval: 3600
- area: null
  category: science
  country: us
  dataset: null
  domains: null
  enabled: true
  language: en
  last_fetch: null
  max_items: 10
  max_results: null
  method: null
  name: Science AI News
  query: AI research OR artificial intelligence research
  sort_by: null
  sort_order: null
  source_type: newsapi
  task: null
  update_interval: 3600
- area: null
  category: Research Papers with Code
  country: null
  dataset: null
  domains: null
  enabled: true
  language: null
  last_fetch: null
  max_items: 15
  max_results: null
  method: null
  name: Papers with Code - Computer Vision
  query: null
  sort_by: null
  sort_order: null
  source_type: paperswithcode
  task: Computer Vision
  update_interval: 3600
- area: null
  category: Research Papers with Code
  country: null
  dataset: null
  domains: null
  enabled: true
  language: null
  last_fetch: null
  max_items: 15
  max_results: null
  method: null
  name: Papers with Code - NLP
  query: null
  sort_by: null
  sort_order: null
  source_type: paperswithcode
  task: Natural Language Processing
  update_interval: 3600
- area: null
  category: Research Papers with Code
  country: null
  dataset: null
  domains: null
  enabled: true
  language: null
  last_fetch: null
  max_items: 15
  max_results: null
  method: null
  name: Papers with Code - Machine Learning
  query: null
  sort_by: null
  sort_order: null
  source_type: paperswithcode
  task: Machine Learning
  update_interval: 3600
