rss_sources:
  - category: Technology
    enabled: true
    last_fetch: null
    last_hash: null
    max_items: 8
    name: MIT Technology Review AI
    update_interval: 3600
    url: https://www.technologyreview.com/feed/ai/
  - category: Technology
    enabled: true
    last_fetch: "2025-08-26T07:02:31.706138"
    last_hash: c1715b54e7737da42bbf589cb55918b5
    max_items: 8
    name: TechCrunch AI
    update_interval: 1800
    url: https://techcrunch.com/tag/artificial-intelligence/feed/
  - category: Technology
    enabled: true
    last_fetch: "2025-08-26T07:02:32.928729"
    last_hash: 122487cda9168f89423e78acf6022384
    max_items: 8
    name: VentureBeat AI
    update_interval: 1800
    url: https://venturebeat.com/category/ai/feed/
  - category: Technology
    enabled: true
    last_fetch: "2025-08-26T07:02:35.151316"
    last_hash: d573c3aaf594c6b005a3600befb5fdcb
    max_items: 6
    name: Ars Technica AI
    update_interval: 3600
    url: https://feeds.arstechnica.com/arstechnica/technology-lab
  - category: Technology
    enabled: true
    last_fetch: "2025-08-26T07:02:36.386962"
    last_hash: 3cf04b88a77753430a710f4a5b98c1c5
    max_items: 6
    name: Wired AI
    update_interval: 3600
    url: https://www.wired.com/feed/rss
